baseURL = "http://caia.art/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "3"
summaryLength = "15"
theme = ""
title = "Caia"
[markup.goldmark.renderer]
unsafe = true
[menu]
footer_right = []
[[menu.footer_left]]
URL = "blog"
name = "News"
[[menu.footer_left]]
URL = "/"
name = "About Us"
[[menu.footer_middle]]
URL = "faq"
name = "FAQ"
[[menu.footer_middle]]
URL = "terms-conditions"
name = "Terms & Conditions"
[[menu.footer_middle]]
URL = "privacy-policy"
name = "Privacy Policy"
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 1
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.main]]
URL = "faq"
name = "FAQ"
weight = 4
[params]
author = "New Co."
contact_form_action = "#"
copyright = "New Co. All Rights Reserved"
description = "This is a fancy New Co. Tagline"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
footer_menu_left = "New Co."
footer_menu_middle = "Support"
footer_menu_right = ""
logo = "images/logo.png"
logo_width = "200px"
social = []
[params.navigation_button]
enable = true
label = "Get in touch"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = false
preloader = ""
